"""
receiver_api.py — Receiver HTTP + TCP server for the C/S split architecture

Runs two servers in the same process:
  - TCP server on port 9999: receives encrypted weather frames, decrypts, stores result
  - HTTP server on port 8081: serves receiver web UI and /api/weather/latest endpoint

Usage:
    python receiver_api.py              # HTTP on 8081, TCP on 9999
    python receiver_api.py --port 9090  # custom HTTP port
    python receiver_api.py --tcp-port 10000  # custom TCP port

API endpoints:
    GET /                    -> web/receiver.html
    GET /css/*, /js/*        -> static files
    GET /api/weather/latest  -> latest received frame data
    POST /api/weather/pcap   -> generate .pcap from latest data
    GET /captures/*           -> PCAP file download
"""

import sys
import os
import json
import time
import socket
import socketserver
import threading
import argparse
from http.server import HTTPServer, BaseHTTPRequestHandler
from socketserver import ThreadingMixIn

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from crypto.rsa_crypto import generate_keypair
from network.weather_server import handle_weather_connection, generate_pcap
from data.weather_data import CITIES as WEATHER_CITIES

# ---------------------------------------------------------------------------
# Global state — RSA keypair (generated by receiver on startup)
# ---------------------------------------------------------------------------

_public_key = None   # {"n": int, "e": int}
_private_key = None  # {"n": int, "d": int}

_latest_result = {}
_latest_result_lock = threading.Lock()
_has_result = threading.Event()

# ---------------------------------------------------------------------------
# TCP Handler
# ---------------------------------------------------------------------------

class WeatherTCPHandler(socketserver.BaseRequestHandler):
    """Handles one TCP connection: receive encrypted frame, decrypt, store result."""

    def handle(self):
        global _latest_result
        try:
            result = handle_weather_connection(self.request, _private_key)
            with _latest_result_lock:
                _latest_result.clear()
                _latest_result.update(result)
                _latest_result["received_at"] = time.strftime("%Y-%m-%d %H:%M:%S")
                # Remove non-JSON-serializable entries
                _latest_result.pop("http_response_bytes", None)
            _has_result.set()
            if result["accepted"]:
                self.request.sendall(b"ACCEPT")
            else:
                self.request.sendall(b"REJECT")
        except Exception:
            with _latest_result_lock:
                _latest_result = {"accepted": False, "error": "Handler exception", "received_at": time.strftime("%Y-%m-%d %H:%M:%S")}
            _has_result.set()
            try:
                self.request.sendall(b"REJECT")
            except Exception:
                pass


class ThreadedTCPServer(socketserver.ThreadingTCPServer):
    allow_reuse_address = True
    daemon_threads = True


def start_tcp_server(host="127.0.0.1", port=9999):
    """Start the TCP server in a daemon thread."""
    server = ThreadedTCPServer((host, port), WeatherTCPHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    print(f"  [TCP] Listening for encrypted frames on {host}:{port}")
    return server


# ---------------------------------------------------------------------------
# HTTP API handlers
# ---------------------------------------------------------------------------

def handle_latest(body: dict) -> dict:
    """Return the latest received frame data."""
    with _latest_result_lock:
        if not _latest_result:
            return {"available": False, "error": "No data received yet"}
        return {"available": True, "data": dict(_latest_result)}


def handle_pcap(body: dict) -> dict:
    """Generate a .pcap file from the latest received data."""
    with _latest_result_lock:
        if not _latest_result or not _latest_result.get("accepted"):
            return {"error": "No accepted data available for PCAP generation"}
        result = dict(_latest_result)

    json_data = result.get("json_data")
    if not json_data:
        return {"error": "No JSON data in latest result"}

    city = json_data.get("city", "Unknown")
    json_bytes = json.dumps(json_data, ensure_ascii=False, indent=2).encode("utf-8")

    try:
        pcap_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "captures")
        pcap_path = generate_pcap(json_bytes, city, pcap_dir)
        pcap_filename = os.path.basename(pcap_path)
        return {
            "success": True,
            "pcap_file": pcap_path,
            "pcap_filename": pcap_filename,
            "download_url": f"/captures/{pcap_filename}",
        }
    except Exception as e:
        return {"error": f"PCAP generation failed: {e}"}


def handle_public_key(body: dict) -> dict:
    """Return the receiver's RSA public key for sender to encrypt."""
    global _public_key
    return {
        "n": format(_public_key["n"], "x"),
        "e": _public_key["e"],
    }


# ---------------------------------------------------------------------------
# HTTP Handler
# ---------------------------------------------------------------------------

_API_HANDLERS = {
    "weather/latest": handle_latest,
    "weather/pcap": handle_pcap,
    "weather/public-key": handle_public_key,
}

_WEB_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "web")

_MIME_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".json": "application/json",
    ".png": "image/png",
    ".svg": "image/svg+xml",
}


class ReceiverHTTPHandler(BaseHTTPRequestHandler):
    """HTTP request handler for the Receiver web UI."""

    def log_message(self, format, *args):
        pass  # suppress default stderr logging

    def do_GET(self):
        path = self.path.split("?")[0]

        if path == "/" or path == "/index.html" or path == "/receiver.html":
            self._serve_file("receiver.html")
        elif path.startswith("/css/") or path.startswith("/js/"):
            self._serve_file(path[1:])
        elif path.startswith("/captures/"):
            self._serve_capture(path[len("/captures/"):])
        elif path == "/api/weather/latest":
            self._send_json(200, handle_latest({}))
        elif path == "/api/weather/public-key":
            self._send_json(200, handle_public_key({}))
        else:
            self._send_json(404, {"error": "Not found"})

    def do_POST(self):
        path = self.path.split("?")[0]

        if path == "/api/weather/pcap":
            try:
                body = self._read_json_body()
                result = handle_pcap(body)
                status = 200 if "error" not in result else 400
                self._send_json(status, result)
            except Exception as e:
                self._send_json(500, {"error": str(e)})
        elif path == "/api/weather/public-key":
            self._send_json(200, handle_public_key({}))
        else:
            self._send_json(404, {"error": "Not found"})

    # -- internal helpers --

    def _read_json_body(self) -> dict:
        length = int(self.headers.get("Content-Length", 0))
        if length == 0:
            return {}
        raw = self.rfile.read(length)
        return json.loads(raw)

    def _send_json(self, code: int, data: dict):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _serve_file(self, rel_path: str):
        filepath = os.path.join(_WEB_ROOT, rel_path)
        if not os.path.isfile(filepath):
            self._send_json(404, {"error": "File not found"})
            return
        _, ext = os.path.splitext(rel_path)
        mime = _MIME_TYPES.get(ext, "application/octet-stream")
        with open(filepath, "rb") as f:
            content = f.read()
        self.send_response(200)
        self.send_header("Content-Type", mime)
        self.send_header("Content-Length", str(len(content)))
        self.end_headers()
        self.wfile.write(content)

    def _serve_capture(self, filename: str):
        filepath = os.path.join(os.path.dirname(os.path.abspath(__file__)), "captures", filename)
        if not os.path.isfile(filepath):
            self._send_json(404, {"error": "Capture file not found"})
            return
        _, ext = os.path.splitext(filename)
        mime = "application/vnd.tcpdump.pcap" if ext == ".pcap" else "application/octet-stream"
        with open(filepath, "rb") as f:
            content = f.read()
        self.send_response(200)
        self.send_header("Content-Type", mime)
        self.send_header("Content-Disposition", f'attachment; filename="{filename}"')
        self.send_header("Content-Length", str(len(content)))
        self.end_headers()
        self.wfile.write(content)


class ThreadedHTTPServer(ThreadingMixIn, HTTPServer):
    daemon_threads = True


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Receiver — HTTP UI + TCP decrypt")
    parser.add_argument("--host", default="127.0.0.1", help="HTTP bind address (default: 127.0.0.1)")
    parser.add_argument("--port", type=int, default=8081, help="HTTP bind port (default: 8081)")
    parser.add_argument("--tcp-host", default="127.0.0.1", help="TCP bind address (default: 127.0.0.1)")
    parser.add_argument("--tcp-port", type=int, default=9999, help="TCP bind port (default: 9999)")
    parser.add_argument("--key-bits", type=int, default=2048, help="RSA key size (default: 2048)")
    parser.add_argument("--key-file", default=None, help="Load RSA private key from file (optional — generates new key if not provided)")
    args = parser.parse_args()

    global _public_key, _private_key

    if args.key_file and os.path.isfile(args.key_file):
        # Load existing key pair from file
        from crypto.rsa_crypto import deserialize_private_key, deserialize_public_key
        with open(args.key_file, "rb") as f:
            _private_key = deserialize_private_key(f.read())
        pub_file = args.key_file.replace("_private.", "_public.")
        if os.path.isfile(pub_file):
            with open(pub_file, "rb") as f:
                _public_key = deserialize_public_key(f.read())
        else:
            _public_key = {"n": _private_key["n"], "e": 65537}
        print(f"[Receiver] Loaded existing RSA-{_private_key['n'].bit_length()} key from {args.key_file}")
    else:
        # Generate fresh keypair on startup
        print(f"[Receiver] Generating RSA-{args.key_bits} keypair...")
        t0 = time.monotonic()
        _public_key, _private_key = generate_keypair(args.key_bits)
        gen_time = round(time.monotonic() - t0, 2)
        print(f"[Receiver] Key generation complete ({gen_time}s)")
        print(f"[Receiver] Modulus: {_public_key['n'].bit_length()} bits")

    # Start TCP server (daemon thread)
    tcp_server = start_tcp_server(args.tcp_host, args.tcp_port)

    # Start HTTP server
    http_server = ThreadedHTTPServer((args.host, args.port), ReceiverHTTPHandler)
    print(f"[Receiver] HTTP UI at http://{args.host}:{args.port}")
    print(f"[Receiver] Public key available at http://{args.host}:{args.port}/api/weather/public-key")
    print(f"[Receiver] Press Ctrl+C to stop\n")

    try:
        http_server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down...")
        http_server.shutdown()
        tcp_server.shutdown()


if __name__ == "__main__":
    main()
